/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AttemptedTestsRouteImport } from './routes/attempted-tests'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ResultAttemptIdRouteImport } from './routes/result.$attemptId'
import { Route as ReviewAttemptIdRouteImport } from './routes/review.$attemptId'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptedTestsRoute = AttemptedTestsRouteImport.update({
  id: '/attempted-tests',
  path: '/attempted-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultAttemptIdRoute = ResultAttemptIdRouteImport.update({
  id: '/result/$attemptId',
  path: '/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewAttemptIdRoute = ReviewAttemptIdRouteImport.update({
  id: '/review/$attemptId',
  path: '/review/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/attempted-tests': typeof AttemptedTestsRoute
  '/history': typeof HistoryRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/review/$attemptId': typeof ReviewAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/attempted-tests': typeof AttemptedTestsRoute
  '/history': typeof HistoryRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/review/$attemptId': typeof ReviewAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/attempted-tests': typeof AttemptedTestsRoute
  '/history': typeof HistoryRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/review/$attemptId': typeof ReviewAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/attempted-tests'
    | '/history'
    | '/result/$attemptId'
    | '/review/$attemptId'
    | '/test/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/attempted-tests'
    | '/history'
    | '/result/$attemptId'
    | '/review/$attemptId'
    | '/test/$testId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/attempted-tests'
    | '/history'
    | '/result/$attemptId'
    | '/review/$attemptId'
    | '/test/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AttemptedTestsRoute: typeof AttemptedTestsRoute
  HistoryRoute: typeof HistoryRoute
  ResultAttemptIdRoute: typeof ResultAttemptIdRoute
  ReviewAttemptIdRoute: typeof ReviewAttemptIdRoute
  TestTestIdRoute: typeof TestTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempted-tests': {
      id: '/attempted-tests'
      path: '/attempted-tests'
      fullPath: '/attempted-tests'
      preLoaderRoute: typeof AttemptedTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$attemptId': {
      id: '/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof ResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$attemptId': {
      id: '/review/$attemptId'
      path: '/review/$attemptId'
      fullPath: '/review/$attemptId'
      preLoaderRoute: typeof ReviewAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AttemptedTestsRoute: AttemptedTestsRoute,
  HistoryRoute: HistoryRoute,
  ResultAttemptIdRoute: ResultAttemptIdRoute,
  ReviewAttemptIdRoute: ReviewAttemptIdRoute,
  TestTestIdRoute: TestTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
