/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AttemptedTestsRouteImport } from './routes/attempted-tests'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LiveTestsRouteImport } from './routes/live-tests'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResultAttemptIdRouteImport } from './routes/result.$attemptId'
import { Route as ReviewAttemptIdRouteImport } from './routes/review.$attemptId'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptedTestsRoute = AttemptedTestsRouteImport.update({
  id: '/attempted-tests',
  path: '/attempted-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTestsRoute = LiveTestsRouteImport.update({
  id: '/live-tests',
  path: '/live-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultAttemptIdRoute = ResultAttemptIdRouteImport.update({
  id: '/result/$attemptId',
  path: '/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewAttemptIdRoute = ReviewAttemptIdRouteImport.update({
  id: '/review/$attemptId',
  path: '/review/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/attempted-tests': typeof AttemptedTestsRoute
  '/contact': typeof ContactRoute
  '/history': typeof HistoryRoute
  '/live-tests': typeof LiveTestsRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/review/$attemptId': typeof ReviewAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/attempted-tests': typeof AttemptedTestsRoute
  '/contact': typeof ContactRoute
  '/history': typeof HistoryRoute
  '/live-tests': typeof LiveTestsRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/review/$attemptId': typeof ReviewAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/attempted-tests': typeof AttemptedTestsRoute
  '/contact': typeof ContactRoute
  '/history': typeof HistoryRoute
  '/live-tests': typeof LiveTestsRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/review/$attemptId': typeof ReviewAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/attempted-tests'
    | '/contact'
    | '/history'
    | '/live-tests'
    | '/notes'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/refund'
    | '/terms'
    | '/result/$attemptId'
    | '/review/$attemptId'
    | '/test/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/attempted-tests'
    | '/contact'
    | '/history'
    | '/live-tests'
    | '/notes'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/refund'
    | '/terms'
    | '/result/$attemptId'
    | '/review/$attemptId'
    | '/test/$testId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/attempted-tests'
    | '/contact'
    | '/history'
    | '/live-tests'
    | '/notes'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/refund'
    | '/terms'
    | '/result/$attemptId'
    | '/review/$attemptId'
    | '/test/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AttemptedTestsRoute: typeof AttemptedTestsRoute
  ContactRoute: typeof ContactRoute
  HistoryRoute: typeof HistoryRoute
  LiveTestsRoute: typeof LiveTestsRoute
  NotesRoute: typeof NotesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  ResultAttemptIdRoute: typeof ResultAttemptIdRoute
  ReviewAttemptIdRoute: typeof ReviewAttemptIdRoute
  TestTestIdRoute: typeof TestTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempted-tests': {
      id: '/attempted-tests'
      path: '/attempted-tests'
      fullPath: '/attempted-tests'
      preLoaderRoute: typeof AttemptedTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-tests': {
      id: '/live-tests'
      path: '/live-tests'
      fullPath: '/live-tests'
      preLoaderRoute: typeof LiveTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$attemptId': {
      id: '/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof ResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$attemptId': {
      id: '/review/$attemptId'
      path: '/review/$attemptId'
      fullPath: '/review/$attemptId'
      preLoaderRoute: typeof ReviewAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AttemptedTestsRoute: AttemptedTestsRoute,
  ContactRoute: ContactRoute,
  HistoryRoute: HistoryRoute,
  LiveTestsRoute: LiveTestsRoute,
  NotesRoute: NotesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  ResultAttemptIdRoute: ResultAttemptIdRoute,
  ReviewAttemptIdRoute: ReviewAttemptIdRoute,
  TestTestIdRoute: TestTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
